version: '3.9'
services:
  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/chore-board
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data: