version: '3.9'
services:
  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  api:
    build: 
      context: ./api
    volumes:
      - ./api:/app
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data: