services:
  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  api:
    build: 
      context: ./api
    volumes:
      - ./api:/app
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - db

  web:
    build:
      context: ./web
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules 
    working_dir: /app
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    depends_on:
      - api

volumes:
  db-data:
  web_node_modules: